version: '3.3'

services:
  influxdb:
    image: influxdb:latest
    container_name: horde-influxdb
    ports:
      - '8086:8086'
    volumes:
      - influxdb-storage:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=horde-admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=horde123
      - DOCKER_INFLUXDB_INIT_ORG=horde-org
      - DOCKER_INFLUXDB_INIT_BUCKET=horde-bucket

volumes:
    influxdb-storage: